###
PUT https://learning-material-backend.onrender.com/getting/pdf/
Content-Type: application/json

{
    "name": "new.pdf"
}

###
GET http://localhost:4000/all/pdf/


###
PUT https://learning-material-backend.onrender.com/upload/pdf/
Content-Type: application/json

{
    "filename": "new.pdf",
    "contentType": "pdf",
    "dateTime": "06-06-2024"
}