###
PUT https://learning-material-backend.onrender.com/getting/pdf/
Content-Type: application/json

{
    "name": "new.pdf"
}

###
GET http://localhost:4000/all/pdf/?sort=1


###
PUT http://localhost:4000/upload/pdf/
Content-Type: application/json

{
    "filename": "new.pdf",
    "contentType": "pdf",
    "dateTime": "06-06-2024",
    "tags": ["math", "class-10"],
    "size": "7mb"
}